

services:
  backend:
    build:
      context: ./backend   # path to your backend folder
      dockerfile: Dockerfile
    image: annikhandare/ecom-backend:0.1
    container_name: ecom-backend
    ports:
      - "3000:3000"
    networks:
      - ecom-network

  frontend:
    build:
      context: ./frontend   # path to your frontend folder
      dockerfile: Dockerfile
    image: annikhandare/ecom-frontend:0.1
    container_name: ecom-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
