#docker compose file -- remember to change volume config while running on other systems
#  volumes:
#    -  <path in local system>:<path in container>
#  *****  we use volumes as add on storage utilities on top of containers , simple words volumes === hard disk for containers *****

services:
  backend:
    build:
      context: ./backend   # path to your backend folder
      dockerfile: Dockerfile
    image: annikhandare/ecom-backend:0.1
    container_name: ecom-backend
    volumes:
      -   new-vol:/app/uploads
      -  /home/kayden/.env:/app/.env
    ports:
      - "3000:3000"
    networks:
      - ecom-network

  frontend:
    build:
      context: ./frontend   # path to your frontend folder
      dockerfile: Dockerfile
    image: annikhandare/ecom-frontend:0.1
    container_name: ecom-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

volumes:
  new-vol:
    external:  true
